"""initial schema

Revision ID: ba08cda045cc
Revises: 
Create Date: 2026-06-27 10:54:32.023983
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ba08cda045cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_domain'), 'projects', ['domain'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('default_device', sa.Enum('desktop', 'tablet', 'mobile', name='devicetype'), nullable=False),
    sa.Column('default_category', sa.String(length=100), nullable=True),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('wcag_level', sa.Enum('A', 'AA', 'AAA', name='wcaglevel'), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('weekly_digest', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    op.create_table('audits',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('device', sa.Enum('desktop', 'tablet', 'mobile', name='devicetype'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', 'canceled', name='auditstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('accessibility_score', sa.Integer(), nullable=True),
    sa.Column('performance_score', sa.Integer(), nullable=True),
    sa.Column('seo_score', sa.Integer(), nullable=True),
    sa.Column('best_practices_score', sa.Integer(), nullable=True),
    sa.Column('wcag_score', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audits_domain'), 'audits', ['domain'], unique=False)
    op.create_index(op.f('ix_audits_project_id'), 'audits', ['project_id'], unique=False)
    op.create_index(op.f('ix_audits_status'), 'audits', ['status'], unique=False)
    op.create_index(op.f('ix_audits_user_id'), 'audits', ['user_id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_audit_id'), 'activity_logs', ['audit_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('pages',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=True),
    sa.Column('load_time_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('num_links', sa.Integer(), nullable=False),
    sa.Column('num_images', sa.Integer(), nullable=False),
    sa.Column('num_forms', sa.Integer(), nullable=False),
    sa.Column('num_buttons', sa.Integer(), nullable=False),
    sa.Column('num_headings', sa.Integer(), nullable=False),
    sa.Column('has_nav', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_audit_id'), 'pages', ['audit_id'], unique=False)
    op.create_table('reports',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('format', sa.Enum('html', 'pdf', 'json', name='reportformat'), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_audit_id'), 'reports', ['audit_id'], unique=False)
    op.create_table('wcag_reports',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('principle', sa.Enum('perceivable', 'operable', 'understandable', 'robust', name='wcagprinciple'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wcag_reports_audit_id'), 'wcag_reports', ['audit_id'], unique=False)
    op.create_table('accessibility_reports',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('violations', sa.Integer(), nullable=False),
    sa.Column('passes', sa.Integer(), nullable=False),
    sa.Column('incomplete', sa.Integer(), nullable=False),
    sa.Column('inapplicable', sa.Integer(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessibility_reports_audit_id'), 'accessibility_reports', ['audit_id'], unique=False)
    op.create_index(op.f('ix_accessibility_reports_page_id'), 'accessibility_reports', ['page_id'], unique=False)
    op.create_table('findings',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('critical', 'serious', 'moderate', 'minor', name='findingseverity'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('source', sa.Enum('axe', 'lighthouse', 'heuristic', name='findingsource'), nullable=False),
    sa.Column('selector', sa.Text(), nullable=True),
    sa.Column('html_snippet', sa.Text(), nullable=True),
    sa.Column('help_url', sa.String(length=1024), nullable=True),
    sa.Column('wcag_criterion', sa.String(length=20), nullable=True),
    sa.Column('wcag_level', sa.Enum('A', 'AA', 'AAA', name='wcaglevel'), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_review', 'resolved', name='findingstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_audit_id'), 'findings', ['audit_id'], unique=False)
    op.create_index(op.f('ix_findings_page_id'), 'findings', ['page_id'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_index(op.f('ix_findings_wcag_criterion'), 'findings', ['wcag_criterion'], unique=False)
    op.create_table('performance_reports',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=True),
    sa.Column('performance_score', sa.Integer(), nullable=True),
    sa.Column('accessibility_score', sa.Integer(), nullable=True),
    sa.Column('seo_score', sa.Integer(), nullable=True),
    sa.Column('best_practices_score', sa.Integer(), nullable=True),
    sa.Column('lcp_ms', sa.Integer(), nullable=True),
    sa.Column('fcp_ms', sa.Integer(), nullable=True),
    sa.Column('tbt_ms', sa.Integer(), nullable=True),
    sa.Column('tti_ms', sa.Integer(), nullable=True),
    sa.Column('speed_index_ms', sa.Integer(), nullable=True),
    sa.Column('cls', sa.Float(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_reports_audit_id'), 'performance_reports', ['audit_id'], unique=False)
    op.create_index(op.f('ix_performance_reports_page_id'), 'performance_reports', ['page_id'], unique=False)
    op.create_table('screenshots',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=True),
    sa.Column('device', sa.Enum('desktop', 'tablet', 'mobile', name='devicetype'), nullable=False),
    sa.Column('kind', sa.Enum('full_page', 'viewport', 'element', name='screenshotkind'), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('thumb_path', sa.String(length=1024), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screenshots_audit_id'), 'screenshots', ['audit_id'], unique=False)
    op.create_index(op.f('ix_screenshots_page_id'), 'screenshots', ['page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screenshots_page_id'), table_name='screenshots')
    op.drop_index(op.f('ix_screenshots_audit_id'), table_name='screenshots')
    op.drop_table('screenshots')
    op.drop_index(op.f('ix_performance_reports_page_id'), table_name='performance_reports')
    op.drop_index(op.f('ix_performance_reports_audit_id'), table_name='performance_reports')
    op.drop_table('performance_reports')
    op.drop_index(op.f('ix_findings_wcag_criterion'), table_name='findings')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_page_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_audit_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_accessibility_reports_page_id'), table_name='accessibility_reports')
    op.drop_index(op.f('ix_accessibility_reports_audit_id'), table_name='accessibility_reports')
    op.drop_table('accessibility_reports')
    op.drop_index(op.f('ix_wcag_reports_audit_id'), table_name='wcag_reports')
    op.drop_table('wcag_reports')
    op.drop_index(op.f('ix_reports_audit_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_pages_audit_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_audit_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_audits_user_id'), table_name='audits')
    op.drop_index(op.f('ix_audits_status'), table_name='audits')
    op.drop_index(op.f('ix_audits_project_id'), table_name='audits')
    op.drop_index(op.f('ix_audits_domain'), table_name='audits')
    op.drop_table('audits')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_domain'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
